# multi nodes provider
IMAGE_NAME = "ubuntu/focal64"
N = 4

$setpublickey = <<-SCRIPT
cat /vagrant/id_rsa.pub >> /root/.ssh/authorized_keys
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end

  (1..N).each do |i|
    config.vm.define "node-#{i}" do |node|
        node.vm.box = IMAGE_NAME
        node.vm.network "private_network", ip: "10.10.20.#{i + 10}"
        node.vm.hostname = "node-#{i}"
        node.vm.provision "shell", inline: $setpublickey
    end
  end

end